version: 2
updates:
  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Smart Contracts
  - package-ecosystem: "npm"
    directory: "/contracts/ethereum"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # API Gateway
  - package-ecosystem: "npm"
    directory: "/backend/api-gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Frontend
  - package-ecosystem: "npm"
    directory: "/frontend/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Queen AI Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend/queen-ai"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
